export const PROSE_CLASS = [
  '[&_h1]:mt-8 [&_h1]:text-3xl [&_h1]:font-black [&_h1]:leading-tight [&_h1:first-child]:mt-0',
  '[&_h2]:mt-12 [&_h2]:inline-block [&_h2]:rounded [&_h2]:bg-lime-300 [&_h2]:px-3 [&_h2]:py-1.5 [&_h2]:text-xl [&_h2]:font-bold [&_h2]:leading-tight [&_h2]:text-zinc-900 [&_h2:first-child]:mt-0',
  '[&_h3]:mt-8 [&_h3]:text-xl [&_h3]:font-bold [&_h3]:leading-tight [&_h3:first-child]:mt-0',
  '[&_p]:mt-4 [&_p]:leading-7 [&_p]:text-muted-foreground [&_p:first-child]:mt-0',
  '[&_ul]:mt-4 [&_ul]:list-disc [&_ul]:space-y-1.5 [&_ul]:pl-6 [&_ul]:marker:text-[#FBBF24]',
  '[&_ol]:mt-4 [&_ol]:list-decimal [&_ol]:space-y-1.5 [&_ol]:pl-6 [&_ol]:marker:text-[#FBBF24]',
  '[&_li]:leading-7 [&_li]:text-muted-foreground',
  '[&_blockquote]:mt-4 [&_blockquote]:border-l-4 [&_blockquote]:border-[#FBBF24]/50 [&_blockquote]:bg-[#FBBF24]/5 [&_blockquote]:py-2 [&_blockquote]:pl-4 [&_blockquote]:italic [&_blockquote]:text-muted-foreground',
  '[&_code:not(pre_code)]:rounded-md [&_code:not(pre_code)]:border [&_code:not(pre_code)]:border-rose-500/20 [&_code:not(pre_code)]:bg-rose-500/10 [&_code:not(pre_code)]:px-1.5 [&_code:not(pre_code)]:py-0.5 [&_code:not(pre_code)]:font-mono [&_code:not(pre_code)]:text-[0.85em] [&_code:not(pre_code)]:text-rose-600 dark:[&_code:not(pre_code)]:text-rose-400',
  '[&_pre]:mt-4 [&_pre]:overflow-x-auto [&_pre]:rounded-xl [&_pre]:bg-[#1f1f20] [&_pre]:p-4 [&_pre]:font-mono [&_pre]:text-[0.85rem] [&_pre]:leading-6 [&_pre]:text-zinc-200',
  '[&_pre_code]:rounded-none [&_pre_code]:border-0 [&_pre_code]:bg-transparent [&_pre_code]:p-0 [&_pre_code]:text-inherit',
  '[&_a]:font-medium [&_a]:text-amber-700 [&_a]:underline [&_a]:underline-offset-4 dark:[&_a]:text-[#FBBF24]',
  '[&_hr]:my-8 [&_hr]:border-border',
  '[&_strong]:font-semibold [&_strong]:text-foreground',
  '[&_img]:my-4 [&_img]:w-full [&_img]:rounded-xl [&_img]:border',
  '[&_table]:mt-6 [&_table]:w-full [&_table]:border-collapse [&_table]:overflow-hidden [&_table]:rounded-xl [&_table]:border [&_table]:text-left [&_table]:text-sm',
  '[&_thead]:bg-muted/50',
  '[&_th]:border-b [&_th]:px-4 [&_th]:py-2.5 [&_th]:font-semibold [&_th]:text-foreground',
  '[&_td]:border-b [&_td]:border-t-0 [&_td]:px-4 [&_td]:py-2.5 [&_td]:text-muted-foreground',
  '[&_tr:last-child_td]:border-b-0',
].join(' ');
